# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encryptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encryptor(object):
    def setupUi(self, Encryptor):
        Encryptor.setObjectName("Encryptor")
        Encryptor.resize(1440, 872)
        self.verticalLayoutWidget = QtWidgets.QWidget(Encryptor)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 1411, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.productLabel = QtWidgets.QLabel(self.widget)
        self.productLabel.setGeometry(QtCore.QRect(179, 10, 961, 20))
        self.productLabel.setObjectName("productLabel")
        self.encryptorListWidget = QtWidgets.QListWidget(self.widget)
        self.encryptorListWidget.setGeometry(QtCore.QRect(-5, 40, 1421, 531))
        self.encryptorListWidget.setObjectName("encryptorListWidget")
        self.changeContentButton = QtWidgets.QPushButton(self.widget)
        self.changeContentButton.setGeometry(QtCore.QRect(-8, 570, 1431, 51))
        self.changeContentButton.setObjectName("changeContentButton")
        self.outputDirectoryButton = QtWidgets.QPushButton(self.widget)
        self.outputDirectoryButton.setGeometry(QtCore.QRect(-8, 610, 1431, 51))
        self.outputDirectoryButton.setObjectName("outputDirectoryButton")
        self.startEncryptionButton = QtWidgets.QPushButton(self.widget)
        self.startEncryptionButton.setGeometry(QtCore.QRect(-10, 690, 1431, 51))
        self.startEncryptionButton.setObjectName("startEncryptionButton")
        self.outputDirectoryLabel = QtWidgets.QLabel(self.widget)
        self.outputDirectoryLabel.setGeometry(QtCore.QRect(10, 660, 1381, 31))
        self.outputDirectoryLabel.setStyleSheet("")
        self.outputDirectoryLabel.setObjectName("outputDirectoryLabel")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Encryptor)
        QtCore.QMetaObject.connectSlotsByName(Encryptor)

    def retranslateUi(self, Encryptor):
        _translate = QtCore.QCoreApplication.translate
        Encryptor.setWindowTitle(_translate("Encryptor", "Form"))
        self.productLabel.setText(_translate("Encryptor", "Header"))
        self.changeContentButton.setText(_translate("Encryptor", "CHANGE CONTENT"))
        self.outputDirectoryButton.setText(_translate("Encryptor", "OUTPUT DIRECTORY"))
        self.startEncryptionButton.setText(_translate("Encryptor", "START ENCRYPTION"))
        self.outputDirectoryLabel.setText(_translate("Encryptor", "Output Directory: "))
