# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(724, 634)
        loginDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        loginDialog.setStyleSheet("background: white;")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(loginDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(loginDialog)
        self.label.setMinimumSize(QtCore.QSize(700, 0))
        self.label.setMaximumSize(QtCore.QSize(700, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#5968B0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame = QtWidgets.QFrame(loginDialog)
        self.frame.setMinimumSize(QtCore.QSize(700, 250))
        self.frame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame.setStyleSheet("border: 1px solid grey;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameEdit = QtWidgets.QLineEdit(self.frame)
        self.usernameEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.usernameEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.usernameEdit.setObjectName("usernameEdit")
        self.verticalLayout.addWidget(self.usernameEdit)
        self.passwordEdit = QtWidgets.QLineEdit(self.frame)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit)
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setMinimumSize(QtCore.QSize(400, 50))
        self.loginButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("background: #5968B0;\n"
"color:white;")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(loginDialog)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame_2.setStyleSheet("border: 1px solid grey;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.createAccountButton = QtWidgets.QPushButton(self.frame_2)
        self.createAccountButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.createAccountButton.setFont(font)
        self.createAccountButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createAccountButton.setStyleSheet("background: #6c757d;\n"
"color: white;")
        self.createAccountButton.setObjectName("createAccountButton")
        self.verticalLayout_2.addWidget(self.createAccountButton)
        self.forgotPasswordButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.forgotPasswordButton.setFont(font)
        self.forgotPasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgotPasswordButton.setStyleSheet("color:#5968B0;\n"
"border: 0px;")
        self.forgotPasswordButton.setFlat(True)
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.verticalLayout_2.addWidget(self.forgotPasswordButton)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(loginDialog)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "Tafa Encryptor Login"))
        self.label.setText(_translate("loginDialog", "TAFA ENCRYPTOR"))
        self.usernameEdit.setPlaceholderText(_translate("loginDialog", "Username"))
        self.passwordEdit.setPlaceholderText(_translate("loginDialog", "Password"))
        self.loginButton.setText(_translate("loginDialog", "LOGIN"))
        self.createAccountButton.setText(_translate("loginDialog", "Don\'t have an account, Create Now"))
        self.forgotPasswordButton.setText(_translate("loginDialog", "Forgot your password? Reset Now"))
