# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encryptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1441, 851))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setStyleSheet("background: white;\n"
"color: #6B62AB;\n"
"font: 24pt \"Comic Sans MS\";")
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.homeTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 0, 1441, 811))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.homeVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.homeVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.homeVerticalLayout.setObjectName("homeVerticalLayout")
        self.homeMainWidget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.homeMainWidget.setObjectName("homeMainWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.homeMainWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1429, 42))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.homeHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.homeHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.homeHorizontalLayout.setObjectName("homeHorizontalLayout")
        self.selectFilesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectFilesButton.setStyleSheet("background: #6B62AB;\n"
"color: white;")
        self.selectFilesButton.setObjectName("selectFilesButton")
        self.homeHorizontalLayout.addWidget(self.selectFilesButton, 0, QtCore.Qt.AlignTop)
        self.selectFolderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectFolderButton.setStyleSheet("background: #6B62AB;\n"
"color: white;")
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.homeHorizontalLayout.addWidget(self.selectFolderButton, 0, QtCore.Qt.AlignTop)
        self.clearFilesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clearFilesButton.setObjectName("clearFilesButton")
        self.homeHorizontalLayout.addWidget(self.clearFilesButton, 0, QtCore.Qt.AlignTop)
        self.createSelectProductButton = QtWidgets.QPushButton(self.homeMainWidget)
        self.createSelectProductButton.setGeometry(QtCore.QRect(-10, 760, 1441, 42))
        self.createSelectProductButton.setStyleSheet("background: #6B62AB;\n"
"color: white;")
        self.createSelectProductButton.setObjectName("createSelectProductButton")
        self.homeAltWidget = QtWidgets.QWidget(self.homeMainWidget)
        self.homeAltWidget.setGeometry(QtCore.QRect(-1, 59, 1431, 691))
        self.homeAltWidget.setObjectName("homeAltWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.homeAltWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 0, 1421, 691))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.altWidgetLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.altWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.altWidgetLayout.setObjectName("altWidgetLayout")
        self.homeVerticalLayout.addWidget(self.homeMainWidget)
        self.tabWidget.addTab(self.homeTab, "")
        self.profileTab = QtWidgets.QWidget()
        self.profileTab.setObjectName("profileTab")
        self.tabWidget.addTab(self.profileTab, "")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.tabWidget.addTab(self.aboutTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFilesButton.setText(_translate("MainWindow", "Select Files"))
        self.selectFolderButton.setText(_translate("MainWindow", "Select Folder"))
        self.clearFilesButton.setText(_translate("MainWindow", "Clear Files"))
        self.createSelectProductButton.setText(_translate("MainWindow", "Create or Select Product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profileTab), _translate("MainWindow", "Profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Help"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
