# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationForm(object):
    def setupUi(self, registrationForm):
        registrationForm.setObjectName("registrationForm")
        registrationForm.resize(780, 685)
        registrationForm.setStyleSheet("background: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(registrationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(registrationForm)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #5968B0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.firstNameInput = QtWidgets.QLineEdit(registrationForm)
        self.firstNameInput.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.firstNameInput.setFont(font)
        self.firstNameInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;\n"
"")
        self.firstNameInput.setObjectName("firstNameInput")
        self.horizontalLayout.addWidget(self.firstNameInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lastNameInput = QtWidgets.QLineEdit(registrationForm)
        self.lastNameInput.setMinimumSize(QtCore.QSize(0, 50))
        self.lastNameInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lastNameInput.setFont(font)
        self.lastNameInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;")
        self.lastNameInput.setObjectName("lastNameInput")
        self.horizontalLayout.addWidget(self.lastNameInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.emailAddressInput = QtWidgets.QLineEdit(registrationForm)
        self.emailAddressInput.setMinimumSize(QtCore.QSize(0, 50))
        self.emailAddressInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.emailAddressInput.setFont(font)
        self.emailAddressInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;\n"
"")
        self.emailAddressInput.setObjectName("emailAddressInput")
        self.verticalLayout.addWidget(self.emailAddressInput)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.phoneInput = QtWidgets.QLineEdit(registrationForm)
        self.phoneInput.setMinimumSize(QtCore.QSize(0, 50))
        self.phoneInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.phoneInput.setFont(font)
        self.phoneInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;\n"
"")
        self.phoneInput.setObjectName("phoneInput")
        self.verticalLayout.addWidget(self.phoneInput)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.passwordInput = QtWidgets.QLineEdit(registrationForm)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 50))
        self.passwordInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;\n"
"")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.confirmPasswordInput = QtWidgets.QLineEdit(registrationForm)
        self.confirmPasswordInput.setMinimumSize(QtCore.QSize(0, 50))
        self.confirmPasswordInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirmPasswordInput.setFont(font)
        self.confirmPasswordInput.setStyleSheet("color: black;\n"
"border: 1px solid grey;\n"
"")
        self.confirmPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordInput.setObjectName("confirmPasswordInput")
        self.verticalLayout.addWidget(self.confirmPasswordInput)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.registerUserButton = QtWidgets.QPushButton(registrationForm)
        self.registerUserButton.setMinimumSize(QtCore.QSize(400, 0))
        self.registerUserButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.registerUserButton.setFont(font)
        self.registerUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerUserButton.setStyleSheet("background: #5968B0;\n"
"color:white;\n"
"border: 0px;")
        self.registerUserButton.setObjectName("registerUserButton")
        self.verticalLayout.addWidget(self.registerUserButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.redirectToLoginButton = QtWidgets.QPushButton(registrationForm)
        self.redirectToLoginButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.redirectToLoginButton.setFont(font)
        self.redirectToLoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redirectToLoginButton.setStyleSheet("background: #6c757d;\n"
"color: white;\n"
"border: 0px;")
        self.redirectToLoginButton.setObjectName("redirectToLoginButton")
        self.verticalLayout.addWidget(self.redirectToLoginButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)

        self.retranslateUi(registrationForm)
        QtCore.QMetaObject.connectSlotsByName(registrationForm)

    def retranslateUi(self, registrationForm):
        _translate = QtCore.QCoreApplication.translate
        registrationForm.setWindowTitle(_translate("registrationForm", "Dialog"))
        self.label.setText(_translate("registrationForm", "TAFA ENCRYPTOR"))
        self.firstNameInput.setPlaceholderText(_translate("registrationForm", "First Name"))
        self.lastNameInput.setPlaceholderText(_translate("registrationForm", "Last Name"))
        self.emailAddressInput.setPlaceholderText(_translate("registrationForm", "Email Address"))
        self.phoneInput.setPlaceholderText(_translate("registrationForm", "Phone Number"))
        self.passwordInput.setPlaceholderText(_translate("registrationForm", "Password"))
        self.confirmPasswordInput.setPlaceholderText(_translate("registrationForm", "Confirm Password"))
        self.registerUserButton.setText(_translate("registrationForm", "REGISTER"))
        self.redirectToLoginButton.setText(_translate("registrationForm", "Already have an account, Login"))
