# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationForm(object):
    def setupUi(self, registrationForm):
        registrationForm.setObjectName("registrationForm")
        registrationForm.setWindowModality(QtCore.Qt.WindowModal)
        registrationForm.resize(750, 700)
        registrationForm.setMaximumSize(QtCore.QSize(750, 700))
        self.verticalLayoutWidget = QtWidgets.QWidget(registrationForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setStyleSheet("background: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.emailAddressInput = QtWidgets.QLineEdit(self.frame)
        self.emailAddressInput.setGeometry(QtCore.QRect(30, 200, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.emailAddressInput.setFont(font)
        self.emailAddressInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.emailAddressInput.setText("")
        self.emailAddressInput.setObjectName("emailAddressInput")
        self.firstNameInput = QtWidgets.QLineEdit(self.frame)
        self.firstNameInput.setGeometry(QtCore.QRect(30, 110, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.firstNameInput.setFont(font)
        self.firstNameInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.firstNameInput.setText("")
        self.firstNameInput.setObjectName("firstNameInput")
        self.lastNameInput = QtWidgets.QLineEdit(self.frame)
        self.lastNameInput.setGeometry(QtCore.QRect(400, 110, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.lastNameInput.setFont(font)
        self.lastNameInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.lastNameInput.setText("")
        self.lastNameInput.setObjectName("lastNameInput")
        self.phoneInput = QtWidgets.QLineEdit(self.frame)
        self.phoneInput.setGeometry(QtCore.QRect(30, 290, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.phoneInput.setFont(font)
        self.phoneInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.phoneInput.setText("")
        self.phoneInput.setObjectName("phoneInput")
        self.passwordInput = QtWidgets.QLineEdit(self.frame)
        self.passwordInput.setGeometry(QtCore.QRect(30, 380, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.confirmPasswordInput = QtWidgets.QLineEdit(self.frame)
        self.confirmPasswordInput.setGeometry(QtCore.QRect(30, 470, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.confirmPasswordInput.setFont(font)
        self.confirmPasswordInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.confirmPasswordInput.setText("")
        self.confirmPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordInput.setObjectName("confirmPasswordInput")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 30, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #5968B0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.registerUserButton = QtWidgets.QPushButton(self.frame)
        self.registerUserButton.setGeometry(QtCore.QRect(260, 550, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.registerUserButton.setFont(font)
        self.registerUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerUserButton.setStyleSheet("background: #5968B0;\n"
"color:white;\n"
"border: 0px;")
        self.registerUserButton.setObjectName("registerUserButton")
        self.redirectToLoginButton = QtWidgets.QPushButton(self.frame)
        self.redirectToLoginButton.setGeometry(QtCore.QRect(140, 620, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.redirectToLoginButton.setFont(font)
        self.redirectToLoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redirectToLoginButton.setStyleSheet("background: #6c757d;\n"
"color: white;\n"
"border: 0px;")
        self.redirectToLoginButton.setObjectName("redirectToLoginButton")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(registrationForm)
        QtCore.QMetaObject.connectSlotsByName(registrationForm)

    def retranslateUi(self, registrationForm):
        _translate = QtCore.QCoreApplication.translate
        registrationForm.setWindowTitle(_translate("registrationForm", "Tafa Encryptor Registration"))
        self.emailAddressInput.setPlaceholderText(_translate("registrationForm", "Email Address"))
        self.firstNameInput.setPlaceholderText(_translate("registrationForm", "First Name"))
        self.lastNameInput.setPlaceholderText(_translate("registrationForm", "Last Name"))
        self.phoneInput.setPlaceholderText(_translate("registrationForm", "Phone"))
        self.passwordInput.setPlaceholderText(_translate("registrationForm", "Password"))
        self.confirmPasswordInput.setPlaceholderText(_translate("registrationForm", "Confirm Password"))
        self.label.setText(_translate("registrationForm", "TAFA ENCRYPTOR"))
        self.registerUserButton.setText(_translate("registrationForm", "REGISTER"))
        self.redirectToLoginButton.setText(_translate("registrationForm", "Already have an account, Login"))
