# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationForm(object):
    def setupUi(self, registrationForm):
        registrationForm.setObjectName("registrationForm")
        registrationForm.setWindowModality(QtCore.Qt.WindowModal)
        registrationForm.resize(750, 700)
        registrationForm.setMaximumSize(QtCore.QSize(750, 700))
        self.verticalLayoutWidget = QtWidgets.QWidget(registrationForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setStyleSheet("background: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.emailAddressInput = QtWidgets.QLineEdit(self.frame)
        self.emailAddressInput.setGeometry(QtCore.QRect(30, 240, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.emailAddressInput.setFont(font)
        self.emailAddressInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.emailAddressInput.setText("")
        self.emailAddressInput.setObjectName("emailAddressInput")
        self.firstNameInput = QtWidgets.QLineEdit(self.frame)
        self.firstNameInput.setGeometry(QtCore.QRect(30, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.firstNameInput.setFont(font)
        self.firstNameInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.firstNameInput.setText("")
        self.firstNameInput.setObjectName("firstNameInput")
        self.lastNameInput = QtWidgets.QLineEdit(self.frame)
        self.lastNameInput.setGeometry(QtCore.QRect(400, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.lastNameInput.setFont(font)
        self.lastNameInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.lastNameInput.setText("")
        self.lastNameInput.setObjectName("lastNameInput")
        self.phoneInput = QtWidgets.QLineEdit(self.frame)
        self.phoneInput.setGeometry(QtCore.QRect(30, 330, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.phoneInput.setFont(font)
        self.phoneInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.phoneInput.setText("")
        self.phoneInput.setObjectName("phoneInput")
        self.passwordInput = QtWidgets.QLineEdit(self.frame)
        self.passwordInput.setGeometry(QtCore.QRect(30, 420, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.confirmPasswordInput = QtWidgets.QLineEdit(self.frame)
        self.confirmPasswordInput.setGeometry(QtCore.QRect(30, 510, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.confirmPasswordInput.setFont(font)
        self.confirmPasswordInput.setStyleSheet("color: black;\n"
"border: 1px solid gray;")
        self.confirmPasswordInput.setText("")
        self.confirmPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordInput.setObjectName("confirmPasswordInput")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 70, 431, 51))
        self.label.setStyleSheet("font: 54pt \"Chalkduster\";\n"
"color: #5968B0;")
        self.label.setObjectName("label")
        self.registerUserButton = QtWidgets.QPushButton(self.frame)
        self.registerUserButton.setGeometry(QtCore.QRect(290, 580, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.registerUserButton.setFont(font)
        self.registerUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerUserButton.setStyleSheet("background: #5968B0;\n"
"color:white;\n"
"border: 0px;")
        self.registerUserButton.setObjectName("registerUserButton")
        self.redirectToLoginButton = QtWidgets.QPushButton(self.frame)
        self.redirectToLoginButton.setGeometry(QtCore.QRect(190, 640, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.redirectToLoginButton.setFont(font)
        self.redirectToLoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redirectToLoginButton.setStyleSheet("background: #6c757d;\n"
"color: white;\n"
"border: 0px;")
        self.redirectToLoginButton.setObjectName("redirectToLoginButton")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(registrationForm)
        QtCore.QMetaObject.connectSlotsByName(registrationForm)

    def retranslateUi(self, registrationForm):
        _translate = QtCore.QCoreApplication.translate
        registrationForm.setWindowTitle(_translate("registrationForm", "Tafa Player Registration"))
        self.emailAddressInput.setPlaceholderText(_translate("registrationForm", "Email Address"))
        self.firstNameInput.setPlaceholderText(_translate("registrationForm", "First Name"))
        self.lastNameInput.setPlaceholderText(_translate("registrationForm", "Last Name"))
        self.phoneInput.setPlaceholderText(_translate("registrationForm", "Phone"))
        self.passwordInput.setPlaceholderText(_translate("registrationForm", "Password"))
        self.confirmPasswordInput.setPlaceholderText(_translate("registrationForm", "Confirm Password"))
        self.label.setText(_translate("registrationForm", "TAFA PLAYER"))
        self.registerUserButton.setText(_translate("registrationForm", "REGISTER"))
        self.redirectToLoginButton.setText(_translate("registrationForm", "Already have an account, Login"))
